# Generated by Django 5.0 on 2023-12-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('attractions_info', models.ManyToManyField(to='attractions_info.attractionsinfo')),
            ],
        ),
    ]
