# Generated by Django 5.0 on 2023-12-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0002_attraction_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
