# Generated by Django 5.0 on 2023-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_attraction_reviews_attraction_image'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='reviews',
            field=models.ManyToManyField(to='reviews.review'),
        ),
    ]
